/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solid.flow;

/**
 *
 * @author ejer
 */
public class GUI extends javax.swing.JFrame {
    ControlEngine run = new ControlEngine();

    /**
     * Creates new form GUI
     */
    public GUI() {
        run.load("Word.txt");
        initComponents();
        jTextFieldDanish.setText(run.getRandomQuestion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Translator = new javax.swing.JLabel();
        jTextFieldDanish = new javax.swing.JTextField();
        jTextFieldEnglish = new javax.swing.JTextField();
        jButton1Next = new javax.swing.JButton();
        jButton2Guess = new javax.swing.JButton();
        jButton3LookUp = new javax.swing.JButton();
        jButton4New = new javax.swing.JButton();
        jLabel2Correct = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Translator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Translator.setText("Translator");

        jTextFieldDanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDanishActionPerformed(evt);
            }
        });

        jTextFieldEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnglishActionPerformed(evt);
            }
        });

        jButton1Next.setText("Next");
        jButton1Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NextActionPerformed(evt);
            }
        });

        jButton2Guess.setText("Guess");
        jButton2Guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2GuessActionPerformed(evt);
            }
        });

        jButton3LookUp.setText("Look Up");
        jButton3LookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3LookUpActionPerformed(evt);
            }
        });

        jButton4New.setText("New");
        jButton4New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4New)
                                .addComponent(jTextFieldDanish, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(jTextFieldEnglish)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3LookUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2Guess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1Translator, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1Translator)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDanish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Next, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2Guess)
                    .addComponent(jTextFieldEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3LookUp)
                    .addComponent(jButton4New))
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDanishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDanishActionPerformed

    private void jButton4NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4NewActionPerformed
        // TODO add your handling code here:
        String danish;
        String english;
        danish = jTextFieldDanish.getText();
        english = jTextFieldEnglish.getText();
        //tests.>>>>>>>>>>>>>>>>>>>>>>>HERE
        run.add(danish,english);
        int size = run.size();
        System.out.println(size);
        jTextFieldDanish.setText("");
        jTextFieldEnglish.setText("");
        jLabel1.setText("Your word has been saved!");
        run.save("Word.txt");
        //>>>>>>>>>>>>>>>>>>>>>>>>> TEST ENDS!
    }//GEN-LAST:event_jButton4NewActionPerformed

    private void jButton1NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NextActionPerformed
        // TODO add your handling code here:
    jTextFieldDanish.setText(run.getRandomQuestion());
    jTextFieldEnglish.setText("");
    jLabel1.setText("");
    }//GEN-LAST:event_jButton1NextActionPerformed

    private void jButton2GuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2GuessActionPerformed
        // TODO add your handling code here:
        Boolean check;
        check=run.checkGuess(jTextFieldDanish.getText(), jTextFieldEnglish.getText());
        if(check){
            jLabel1.setText("The answer is correct!");
        }else
            jLabel1.setText("The answer is wrong!");
        
    }//GEN-LAST:event_jButton2GuessActionPerformed

    private void jButton3LookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3LookUpActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("The answer is: " + run.lookup(jTextFieldDanish.getText()));
    }//GEN-LAST:event_jButton3LookUpActionPerformed

    private void jTextFieldEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnglishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Next;
    private javax.swing.JButton jButton2Guess;
    private javax.swing.JButton jButton3LookUp;
    private javax.swing.JButton jButton4New;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Translator;
    private javax.swing.JLabel jLabel2Correct;
    private javax.swing.JTextField jTextFieldDanish;
    private javax.swing.JTextField jTextFieldEnglish;
    // End of variables declaration//GEN-END:variables
}
